openapi: 3.0.0
servers:
  - url: https://virtserver.swaggerhub.com/hei-ryan/PROG3_TD2/1.0.0
info:
  version: "latest"
  title: PROG3 - TD2
paths:
  /sponsor:
    get:
      tags:
        - Sponsors
      summary: get all sponsors
      operationId: getSponsors
      responses:
        '200':
          description: List of Sponsors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sponsor'
        '500':
          description: Internal server error    
  /players:
    get:
      tags:
        - Players
      summary: get all players
      operationId: getPlayers
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error           
  /teams:
    get:
      tags:
        - Teams
      summary: get all teams
      operationId: getTeams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error
  /match:
    get:
      tags:
        - Match
      summary: get all match
      operationId: getMatch
      responses:
        '200':
          description: List of match
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error
  /scores:
    get:
      tags:
        - Scores
      summary: get all scores
      operationId: getScores
      responses:
        '200':
          description: List of scores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Score'
        '500':
          description: Internal server error        
components:
  schemas:
    Sponsor:
      type: object
      properties:
        name:
          type: string
        id:
          type: integer  
    Player:
      type: object
      properties:
        id: 
          type: integer
        name:
          type: string
        post:
          type: string  
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        sponsors:
          type: array
          items:
            $ref: '#/components/schemas/Sponsor'  
    Match:
      type: object
      properties:
        id:
          type: integer
        teamA:
          allOf:
            -  $ref: '#/components/schemas/Team' 
        teamB:
          allOf:
            -  $ref: '#/components/schemas/Team'       
        dateTime:
          type: string  
        scores:    
          allOf:
            -  $ref: '#/components/schemas/Score'  
        scoreTeamA:
          type: integer
        scoreTeamB:
          type: integer      
    Score:
      type: object
      properties:
        id:
          type: integer
        matchId:
          type: integer  
        player:
          allOf:
            -  $ref: '#/components/schemas/Player'     
        times:
          type: integer   
        isOS:
          type: boolean